
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import javafx.util.Pair;
import java.util.HashSet;
import java.util.Set;
import java.util.Objects;
import java.util.LinkedList;
import java.io.*;
import java.util.Arrays;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\071\000\002\004\004\000\002\002\004\000\002\004" +
    "\003\000\002\023\012\000\002\016\004\000\002\016\005" +
    "\000\002\016\002\000\002\022\004\000\002\022\003\000" +
    "\002\021\005\000\002\021\003\000\002\021\006\000\002" +
    "\021\011\000\002\021\011\000\002\021\003\000\002\021" +
    "\004\000\002\021\004\000\002\014\004\000\002\014\005" +
    "\000\002\014\002\000\002\037\002\000\002\015\007\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\002" +
    "\005\000\002\002\003\000\002\002\003\000\002\002\003" +
    "\000\002\002\003\000\002\002\003\000\002\002\005\000" +
    "\002\030\004\000\002\034\005\000\002\032\004\000\002" +
    "\032\007\000\002\026\003\000\002\026\005\000\002\026" +
    "\005\000\002\026\003\000\002\024\005\000\002\024\005" +
    "\000\002\024\005\000\002\024\003\000\002\006\003\000" +
    "\002\007\004\000\002\010\004\000\002\012\005\000\002" +
    "\011\004\000\002\013\005\000\002\025\005\000\002\025" +
    "\003\000\002\025\003\000\002\025\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\161\000\012\024\015\025\011\027\020\030\006\001" +
    "\002\000\004\026\uffe8\001\002\000\004\026\uffe6\001\002" +
    "\000\012\024\015\025\011\027\020\030\006\001\002\000" +
    "\014\002\uffff\024\uffff\025\uffff\027\uffff\030\uffff\001\002" +
    "\000\004\026\uffe7\001\002\000\004\026\uffd2\001\002\000" +
    "\014\002\162\024\015\025\011\027\020\030\006\001\002" +
    "\000\004\026\uffeb\001\002\000\004\026\027\001\002\000" +
    "\012\024\015\025\011\027\020\030\006\001\002\000\004" +
    "\026\uffe9\001\002\000\004\026\uffea\001\002\000\010\024" +
    "\022\025\023\030\021\001\002\000\012\024\015\025\011" +
    "\027\020\030\006\001\002\000\012\024\015\025\011\027" +
    "\020\030\006\001\002\000\004\026\uffd1\001\002\000\004" +
    "\026\uffcf\001\002\000\004\026\uffcd\001\002\000\004\026" +
    "\uffd0\001\002\000\004\011\030\001\002\000\014\012\ufffb" +
    "\014\040\024\037\025\011\030\006\001\002\000\004\026" +
    "\155\001\002\000\016\004\uffe0\012\uffe0\014\uffe0\024\uffe0" +
    "\025\uffe0\030\uffe0\001\002\000\020\004\uffe3\012\uffe3\013" +
    "\153\014\uffe3\024\uffe3\025\uffe3\030\uffe3\001\002\000\014" +
    "\012\ufffb\014\040\024\037\025\011\030\006\001\002\000" +
    "\016\004\uffe1\012\uffe1\014\uffe1\024\uffe1\025\uffe1\030\uffe1" +
    "\001\002\000\016\004\uffe2\012\uffe2\014\uffe2\024\uffe2\025" +
    "\uffe2\030\uffe2\001\002\000\012\024\015\025\011\027\020" +
    "\030\006\001\002\000\010\024\037\025\011\030\006\001" +
    "\002\000\020\004\uffe4\012\uffe4\013\144\014\uffe4\024\uffe4" +
    "\025\uffe4\030\uffe4\001\002\000\004\012\045\001\002\000" +
    "\004\026\044\001\002\000\020\004\uffde\012\uffde\013\uffde" +
    "\014\uffde\024\uffde\025\uffde\030\uffde\001\002\000\004\017" +
    "\046\001\002\000\020\004\051\023\052\024\037\025\011" +
    "\026\054\030\006\031\053\001\002\000\004\004\143\001" +
    "\002\000\022\004\051\020\ufff9\023\052\024\037\025\011" +
    "\026\054\030\006\031\053\001\002\000\022\004\ufff7\020" +
    "\ufff7\023\ufff7\024\ufff7\025\ufff7\026\ufff7\030\ufff7\031\ufff7" +
    "\001\002\000\004\011\134\001\002\000\010\011\070\016" +
    "\067\026\071\001\002\000\010\011\063\013\064\021\062" +
    "\001\002\000\022\004\ufff3\020\ufff3\023\ufff3\024\ufff3\025" +
    "\ufff3\026\ufff3\030\ufff3\031\ufff3\001\002\000\004\004\061" +
    "\001\002\000\004\020\060\001\002\000\014\002\ufffe\024" +
    "\ufffe\025\ufffe\027\ufffe\030\ufffe\001\002\000\022\004\ufff1" +
    "\020\ufff1\023\ufff1\024\ufff1\025\ufff1\026\ufff1\030\ufff1\031" +
    "\ufff1\001\002\000\010\011\070\016\067\026\071\001\002" +
    "\000\010\012\uffed\014\uffed\026\uffed\001\002\000\010\011" +
    "\070\016\067\026\071\001\002\000\032\004\uffd3\005\uffd3" +
    "\006\uffd3\007\uffd3\010\uffd3\012\uffd3\014\uffd3\015\uffd3\022" +
    "\uffd3\024\uffd3\025\uffd3\030\uffd3\001\002\000\032\004\uffd7" +
    "\005\uffd7\006\uffd7\007\106\010\105\012\uffd7\014\uffd7\015" +
    "\104\022\uffd7\024\uffd7\025\uffd7\030\uffd7\001\002\000\032" +
    "\004\uffcb\005\uffcb\006\uffcb\007\uffcb\010\uffcb\012\uffcb\014" +
    "\uffcb\015\uffcb\022\uffcb\024\uffcb\025\uffcb\030\uffcb\001\002" +
    "\000\010\011\070\016\067\026\071\001\002\000\036\004" +
    "\uffca\005\uffca\006\uffca\007\uffca\010\uffca\011\063\012\uffca" +
    "\014\uffca\015\uffca\021\101\022\uffca\024\uffca\025\uffca\030" +
    "\uffca\001\002\000\010\004\076\005\074\006\075\001\002" +
    "\000\024\004\uffda\005\uffda\006\uffda\012\uffda\014\uffda\022" +
    "\uffda\024\uffda\025\uffda\030\uffda\001\002\000\010\011\070" +
    "\016\067\026\100\001\002\000\010\011\070\016\067\026" +
    "\100\001\002\000\022\004\ufff6\020\ufff6\023\ufff6\024\ufff6" +
    "\025\ufff6\026\ufff6\030\ufff6\031\ufff6\001\002\000\032\004" +
    "\uffd8\005\uffd8\006\uffd8\007\106\010\105\012\uffd8\014\uffd8" +
    "\015\104\022\uffd8\024\uffd8\025\uffd8\030\uffd8\001\002\000" +
    "\034\004\uffca\005\uffca\006\uffca\007\uffca\010\uffca\012\uffca" +
    "\014\uffca\015\uffca\021\101\022\uffca\024\uffca\025\uffca\030" +
    "\uffca\001\002\000\010\011\070\016\067\026\071\001\002" +
    "\000\010\005\074\006\075\022\103\001\002\000\032\004" +
    "\uffc9\005\uffc9\006\uffc9\007\uffc9\010\uffc9\012\uffc9\014\uffc9" +
    "\015\uffc9\022\uffc9\024\uffc9\025\uffc9\030\uffc9\001\002\000" +
    "\010\011\070\016\067\026\100\001\002\000\010\011\070" +
    "\016\067\026\100\001\002\000\010\011\070\016\067\026" +
    "\100\001\002\000\032\004\uffd6\005\uffd6\006\uffd6\007\uffd6" +
    "\010\uffd6\012\uffd6\014\uffd6\015\uffd6\022\uffd6\024\uffd6\025" +
    "\uffd6\030\uffd6\001\002\000\032\004\uffd5\005\uffd5\006\uffd5" +
    "\007\uffd5\010\uffd5\012\uffd5\014\uffd5\015\uffd5\022\uffd5\024" +
    "\uffd5\025\uffd5\030\uffd5\001\002\000\032\004\uffd4\005\uffd4" +
    "\006\uffd4\007\uffd4\010\uffd4\012\uffd4\014\uffd4\015\uffd4\022" +
    "\uffd4\024\uffd4\025\uffd4\030\uffd4\001\002\000\032\004\uffd9" +
    "\005\uffd9\006\uffd9\007\106\010\105\012\uffd9\014\uffd9\015" +
    "\104\022\uffd9\024\uffd9\025\uffd9\030\uffd9\001\002\000\010" +
    "\005\074\006\075\012\114\001\002\000\032\004\uffcc\005" +
    "\uffcc\006\uffcc\007\uffcc\010\uffcc\012\uffcc\014\uffcc\015\uffcc" +
    "\022\uffcc\024\uffcc\025\uffcc\030\uffcc\001\002\000\010\012" +
    "\uffee\014\116\026\120\001\002\000\004\026\123\001\002" +
    "\000\004\012\122\001\002\000\010\012\uffee\014\116\026" +
    "\120\001\002\000\004\012\ufff0\001\002\000\034\004\uffec" +
    "\005\uffec\006\uffec\012\uffec\014\uffec\020\uffec\022\uffec\023" +
    "\uffec\024\uffec\025\uffec\026\uffec\030\uffec\031\uffec\001\002" +
    "\000\010\012\uffee\014\116\026\120\001\002\000\004\012" +
    "\uffef\001\002\000\010\005\074\006\075\022\126\001\002" +
    "\000\004\013\127\001\002\000\010\011\070\016\067\026" +
    "\071\001\002\000\010\004\131\005\074\006\075\001\002" +
    "\000\022\004\ufff5\020\ufff5\023\ufff5\024\ufff5\025\ufff5\026" +
    "\ufff5\030\ufff5\031\ufff5\001\002\000\010\004\133\005\074" +
    "\006\075\001\002\000\022\004\ufff8\020\ufff8\023\ufff8\024" +
    "\ufff8\025\ufff8\026\ufff8\030\ufff8\031\ufff8\001\002\000\010" +
    "\011\070\016\067\026\071\001\002\000\010\005\074\006" +
    "\075\012\136\001\002\000\004\017\137\001\002\000\020" +
    "\004\051\023\052\024\037\025\011\026\054\030\006\031" +
    "\053\001\002\000\004\020\141\001\002\000\022\004\ufff4" +
    "\020\ufff4\023\ufff4\024\ufff4\025\ufff4\026\ufff4\030\ufff4\031" +
    "\ufff4\001\002\000\004\020\ufffa\001\002\000\022\004\ufff2" +
    "\020\ufff2\023\ufff2\024\ufff2\025\ufff2\026\ufff2\030\ufff2\031" +
    "\ufff2\001\002\000\010\011\070\016\067\026\071\001\002" +
    "\000\022\004\uffe5\005\074\006\075\012\uffe5\014\uffe5\024" +
    "\uffe5\025\uffe5\030\uffe5\001\002\000\014\012\ufffb\014\040" +
    "\024\037\025\011\030\006\001\002\000\004\012\ufffc\001" +
    "\002\000\004\026\151\001\002\000\020\004\uffdd\012\uffdd" +
    "\013\uffdd\014\uffdd\024\uffdd\025\uffdd\030\uffdd\001\002\000" +
    "\004\012\ufffd\001\002\000\010\011\070\016\067\026\071" +
    "\001\002\000\022\004\uffdf\005\074\006\075\012\uffdf\014" +
    "\uffdf\024\uffdf\025\uffdf\030\uffdf\001\002\000\020\004\uffdc" +
    "\012\uffdc\014\uffdc\021\156\024\uffdc\025\uffdc\030\uffdc\001" +
    "\002\000\010\011\070\016\067\026\071\001\002\000\010" +
    "\005\074\006\075\022\160\001\002\000\016\004\uffdb\012" +
    "\uffdb\014\uffdb\024\uffdb\025\uffdb\030\uffdb\001\002\000\014" +
    "\002\001\024\001\025\001\027\001\030\001\001\002\000" +
    "\004\002\000\001\002\000\004\026\uffce\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\161\000\024\004\011\005\013\006\016\007\012\010" +
    "\003\011\004\012\015\013\007\023\006\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\005\162\006\016\007" +
    "\012\010\003\011\004\012\015\013\007\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\005" +
    "\013\006\016\007\012\010\003\011\004\012\015\013\007" +
    "\023\160\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\005\025\006\016\007\012\010\003\011\004\012\015" +
    "\013\007\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\005\024\006\016\007\012\010\003" +
    "\011\004\012\015\013\007\001\001\000\020\005\023\006" +
    "\016\007\012\010\003\011\004\012\015\013\007\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\024\002\033\006\042" +
    "\011\030\016\041\030\040\032\034\033\031\034\032\035" +
    "\035\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\024\002\033\006\042\011\030\016\151\030" +
    "\040\032\034\033\031\034\032\035\035\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\005\147\006\016\007" +
    "\012\010\003\011\004\012\015\013\007\001\001\000\022" +
    "\002\145\006\042\011\030\030\040\032\034\033\031\034" +
    "\032\035\035\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\032\002\046\006\042\011\030\015\054\017\055\021\047" +
    "\022\056\030\040\032\034\033\031\034\032\035\035\001" +
    "\001\000\002\001\001\000\032\002\046\006\042\011\030" +
    "\015\054\017\055\021\047\022\141\030\040\032\034\033" +
    "\031\034\032\035\035\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\015\072\024\065\025\064\026\131\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\015\072\024\065\025\064\026\124\001\001\000\004" +
    "\037\114\001\001\000\012\015\072\024\065\025\064\026" +
    "\071\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\015\072\024\065\025\064\026\112\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\024\111\025\064\001\001\000\006\024\076\025" +
    "\064\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\015\072\024\065\025\064\026\101\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\025\110" +
    "\001\001\000\004\025\107\001\001\000\004\025\106\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\014\116\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\120\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\014\123\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\015\072\024\065\025" +
    "\064\026\127\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\015\072\024" +
    "\065\025\064\026\134\001\001\000\002\001\001\000\002" +
    "\001\001\000\032\002\046\006\042\011\030\015\054\017" +
    "\055\021\047\022\137\030\040\032\034\033\031\034\032" +
    "\035\035\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\015\072\024\065" +
    "\025\064\026\144\001\001\000\002\001\001\000\024\002" +
    "\033\006\042\011\030\016\146\030\040\032\034\033\031" +
    "\034\032\035\035\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\015\072" +
    "\024\065\025\064\026\153\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\015\072\024\065\025\064\026\156" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /** User initialization code. */
    VarFunctionsContext context = new VarFunctionsContext();
    public static void newScope(){
	typenames.push(new HashSet<String>());
    }
    public static void deleteScope(){
	typenames.pop();
    }
    public static boolean lookupType(String name){
	for (HashSet<String> scope: typenames)
	    if (scope.contains(name)) return true;
	return false;
    }
    public static void addType(String name){
        typenames.peek().add(name);
    }
    Set<Pair<String, Integer>> varArray = new HashSet();
    public static LinkedList<HashSet<String>> typenames = new LinkedList<HashSet<String>>();
    public Parser(Lexer lex, ComplexSymbolFactory sf) {
        super(lex,sf);
    }
    /* Change the method report_error so it will display the line and
       column of where the error occurred in the input as well as the
       reason for the error which is passed into the method in the
       String 'message'. */
    public void report_error(String message, Object info) {
   
        /* Create a StringBuilder called 'm' with the string 'Error' in it. */
        StringBuilder m = new StringBuilder("Error");
   
        /* Check if the information passed to the method is the same
           type as the type java_cup.runtime.Symbol. */
        if (info instanceof java_cup.runtime.Symbol) {
            /* Declare a java_cup.runtime.Symbol object 's' with the
               information in the object info that is being typecasted
               as a java_cup.runtime.Symbol object. */
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
   
            /* Check if the line number in the input is greater or
               equal to zero. */
            if (s.left >= 0) {                
                /* Add to the end of the StringBuilder error message
                   the line number of the error in the input. */
                m.append(" in line "+(s.left+1));   
                /* Check if the column number in the input is greater
                   or equal to zero. */
                if (s.right >= 0)                    
                    /* Add to the end of the StringBuilder error message
                       the column number of the error in the input. */
                    m.append(", column "+(s.right+1));
            }
        }
   
        /* Add to the end of the StringBuilder error message created in
           this method the message that was passed into this method. */
        m.append(" : "+message);
   
        /* Print the contents of the StringBuilder 'm', which contains
           an error message, out on a line. */
        System.err.println(m);
    }

   public static class Main {
     static public void main(String argv[]) {
       /* Start the parser */
       try {
         Parser p = new Parser(new Lexer(new FileReader(argv[0])));
         System.out.println("Start parsing");
         p.context.newScope();
         Program result = (Program) p.parse().value;
         p.context.deleteScope();
         System.out.println(p.context.ex(p.context.rootFunc("main")));
         p.context.getFunctions();
         p.context.getVariables();
         System.out.println("Finish parsing");
       } catch (Exception e) {
         /* do cleanup here -- possibly rethrow e */
         System.out.println("");
         e.printStackTrace();
       }
     }
   }
    /* Change the method report_fatal_error so when it reports a fatal
       error it will display the line and column number of where the
       fatal error occurred in the input as well as the reason for the
       fatal error which is passed into the method in the object
       'message' and then exit.*/
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programm ::= programm function 
            {
              Program RESULT =null;
		 RESULT = new Program(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programm",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programm EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programm ::= function 
            {
              Program RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programm",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // function ::= type NAME LPAREN function_parametrs_declaration RPAREN LBRACE function_body RBRACE 
            {
              Opr RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Types t = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int fpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int fpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Opr fp = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr b = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 context.registerFunction(new FunctionDefinition(t, n, fp, b)); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // function_parametrs_declaration ::= initialize function_parametrs_declaration 
            {
              Opr RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr i = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int fpdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fpdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr fpd = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                Opr res = new Opr(NodeType.VAR, operType.NEXTSTMT);
                res.addInListOpr(i);
                if (fpd != null)
                    res.addInListOpr(fpd);
                RESULT = res; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_parametrs_declaration",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // function_parametrs_declaration ::= COMMA initialize function_parametrs_declaration 
            {
              Opr RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr i = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int fpdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fpdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr fpd = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Opr res = new Opr(NodeType.VAR, operType.NEXTSTMT);
                res.addInListOpr(i);
                if (fpd != null)
                    res.addInListOpr(fpd);
                RESULT = res; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_parametrs_declaration",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // function_parametrs_declaration ::= 
            {
              Opr RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_parametrs_declaration",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // function_body ::= statement function_body 
            {
              Opr RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr s = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr b = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                Opr res = new Opr(NodeType.OPR, operType.NEXTSTMT);
                res.addInListOpr(s);
                res.addInListOpr(b);
                RESULT = res; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_body",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // function_body ::= statement 
            {
              Opr RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr s = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Opr res = new Opr(NodeType.OPR);
                res.addInListOpr(s);
                RESULT = res; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_body",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // statement ::= RETURN expr SEMI 
            {
              Opr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr n = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                if (n instanceof Variable) {
                    Opr res = new Opr(NodeType.OPR, operType.RETURN);
                    Variable var = context.getVar(((Variable) n).getName());
                    res.addInListOpr(var);
                    RESULT = res;
                    } else {
                    RESULT = n;
                }
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // statement ::= SEMI 
            {
              Opr RESULT =null;
		 Opr res = new Opr(NodeType.OPR, operType.SEMI);
                 res.addInListOpr(null);
                 RESULT = res;
                 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // statement ::= NAME ASSIGN expr SEMI 
            {
              Opr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr e = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 Opr res = new Opr(NodeType.OPR, operType.ASSIGN);
                Variable var = context.getVar(n);
                res.addInListOpr(var);
                res.addInListOpr(e);
                RESULT = res;
                 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // statement ::= NAME LSQUARE expr RSQUARE ASSIGN expr SEMI 
            {
              Opr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Opr i = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr e = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 Opr res = new Opr(NodeType.OPR, operType.ASSIGN);
                Variable var = context.getVar(n);
                res.addInListOpr(var);
                res.addInListOpr(i);
                res.addInListOpr(e);
                RESULT = res;
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // statement ::= WHILE LPAREN expr RPAREN LBRACE function_body RBRACE 
            {
              Opr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Opr e = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr s = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                Opr res = new Opr(NodeType.OPR, operType.WHILE);
                res.addInListOpr(e);
                res.addInListOpr(s);
                RESULT = res;
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // statement ::= function_call 
            {
              Opr RESULT =null;
		int fcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr fc = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = fc; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // statement ::= initialize SEMI 
            {
              Opr RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr i = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // statement ::= expr_list SEMI 
            {
              Opr RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // function_parametrs ::= NAME function_parametrs 
            {
              Opr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int fpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr fp = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Opr res = new Opr(NodeType.VAR);
                Variable var = context.getVar(n);
                res.addInListOpr(var);
                if (fp != null)
                    res.addInListOpr(fp);
                RESULT = res;
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_parametrs",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // function_parametrs ::= COMMA NAME function_parametrs 
            {
              Opr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int fpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr fp = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                Variable var = context.getVar(n);
                RESULT = var;
                Opr res = new Opr(NodeType.VAR);
                res.addInListOpr(var);
                if (fp != null)
                    res.addInListOpr(fp);
                RESULT = res;
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_parametrs",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // function_parametrs ::= 
            {
              Opr RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_parametrs",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // NT$0 ::= 
            {
              Opr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
 context.newScope(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$0",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // function_call ::= NAME LPAREN NT$0 function_parametrs RPAREN 
            {
              Opr RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Opr) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr p = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                Opr funcParams = context.funcParametrs(n);
                Opr res = new Opr(NodeType.OPR, operType.FUNC_CALL);
                res.addInListOpr(context.rootFunc(n));
                res.addInListOpr(funcParams);
                res.addInListOpr(p);
                RESULT = res;
                context.deleteScope();
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_call",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // type ::= const_value 
            {
              Types RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Types v = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // type ::= value 
            {
              Types RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Types v = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = v; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // type ::= const_pointer 
            {
              Types RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Types p = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // type ::= pointer 
            {
              Types RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Types p = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // type ::= const_array_of 
            {
              Types RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Types a = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // type ::= array_of 
            {
              Types RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Types t = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = t; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // initialize ::= defenition_value ASSIGN expr 
            {
              Opr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Opr e = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr n = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Opr res = new Opr(NodeType.OPR, operType.ASSIGN);
                      res.addInListOpr(e);
                      res.addInListOpr(n);
                      RESULT = res;
                      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("initialize",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // initialize ::= defenition_value 
            {
              Opr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr e = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("initialize",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // initialize ::= defenition_pointer 
            {
              Opr RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr p = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = p; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("initialize",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // initialize ::= defeniniton_const_pointer 
            {
              Opr RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr p = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("initialize",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // initialize ::= defenition_array_of 
            {
              Opr RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr a = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("initialize",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // initialize ::= defenition_const_array_of 
            {
              Opr RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr a = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("initialize",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // initialize ::= defenition_pointer ASSIGN expr 
            {
              Opr RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Opr p = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr e = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Opr res = new Opr(NodeType.OPR, operType.ASSIGN);
                      res.addInListOpr(p);
                      res.addInListOpr(e);
                      RESULT = res;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("initialize",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // defenition_value ::= value NAME 
            {
              Opr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                     Variable var = new Variable(Types.VALUE, n);
                     context.addVar(var);
                     var.setValue(new Const(0));
                     RESULT = var;
                     
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("defenition_value",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // defenition_pointer ::= POINTER type NAME 
            {
              Opr RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Types t = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Variable var = new Variable(Types.POINTER, n);
                     context.addVar(var);
                     var.setValue(new Variable(t, n));
                     RESULT = var; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("defenition_pointer",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // defenition_array_of ::= array_of NAME 
            {
              Opr RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Types t = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Variable var = new Variable(Types.ARRAY_OF, n);
                    context.addVar(var);
                    Opr res = new Opr(NodeType.VAR);
                    res.addInListOpr(var);
                    res.addInListOpr(new Const(4));
                    RESULT = res;
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("defenition_array_of",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // defenition_array_of ::= array_of NAME LSQUARE expr RSQUARE 
            {
              Opr RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Types t = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr e = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 Variable var = new Variable(Types.ARRAY_OF, n);
                    context.addVar(var);
                    Opr res = new Opr(NodeType.VAR);
                    res.addInListOpr(var);
                    res.addInListOpr(e);
                    RESULT = res;
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("defenition_array_of",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= function_call 
            {
              Opr RESULT =null;
		int fcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr fc = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = fc; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= expr PLUS factor 
            {
              Opr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Opr e = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr f = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  Opr res = new Opr(NodeType.OPR, operType.PLUS);
                  res.addInListOpr(e);
                  res.addInListOpr(f);
                  RESULT = res;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= expr MINUS factor 
            {
              Opr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Opr e = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr f = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Opr res = new Opr(NodeType.OPR, operType.MINUS);
                  res.addInListOpr(e);
                  res.addInListOpr(f);
                  RESULT = res; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= factor 
            {
              Opr RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr f = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // factor ::= factor TIMES term 
            {
              Opr RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Opr f = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr t = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Opr res = new Opr(NodeType.OPR, operType.TIMES);
                  res.addInListOpr(f);
                  res.addInListOpr(t);
                  RESULT = res;
                  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // factor ::= factor DIVIDE term 
            {
              Opr RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Opr f = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr t = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                 Opr res = new Opr(NodeType.OPR, operType.DIVIDE);
                 res.addInListOpr(f);
                 res.addInListOpr(t);
                 RESULT = res;
                  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // factor ::= factor MOD term 
            {
              Opr RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Opr f = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr t = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                 Opr res = new Opr(NodeType.OPR, operType.MOD);
                 res.addInListOpr(f);
                 res.addInListOpr(t);
                 RESULT = res;
                 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // factor ::= term 
            {
              Opr RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Opr t = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = t; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // value ::= VALUE 
            {
              Types RESULT =null;
		 RESULT = Types.VALUE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("value",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // const_value ::= CONST VALUE 
            {
              Types RESULT =null;
		 RESULT = Types.CONST_VALUE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("const_value",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // pointer ::= POINTER type 
            {
              Types RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Types t = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = Types.POINTER; RESULT.setType(t); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("pointer",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // const_pointer ::= CONST POINTER type 
            {
              Types RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Types t = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = Types.CONST_POINTER; RESULT.setType(t); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("const_pointer",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // array_of ::= ARRAY_OF type 
            {
              Types RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Types t = (Types)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = t; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("array_of",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // const_array_of ::= CONST ARRAY_OF type 
            {
              Types RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("const_array_of",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // term ::= LPAREN expr RPAREN 
            {
              Opr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr e = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // term ::= NUMBER 
            {
              Opr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (Opr) new Const(n);
                 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // term ::= NAME 
            {
              Opr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Variable var = context.getVar(n);
                 RESULT = var; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // term ::= NAME LSQUARE expr RSQUARE 
            {
              Opr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Opr e = (Opr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 Variable var = context.getVar(n);
                 Opr res = new Opr(NodeType.OPR, operType.TAKE_FROM_ARRAY);
                 res.addInListOpr(var);
                 res.addInListOpr(e);
                 RESULT = res;
                 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
