
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int MOD = 11;
  public static final int PLUS = 3;
  public static final int RBRACE = 14;
  public static final int RPAREN = 8;
  public static final int SEMI = 2;
  public static final int VALUE = 18;
  public static final int RETURN = 22;
  public static final int NAME = 19;
  public static final int LPAREN = 7;
  public static final int LBRACE = 13;
  public static final int COMMA = 10;
  public static final int EOF = 0;
  public static final int NUMBER = 12;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int LSQUARE = 15;
  public static final int CONST = 20;
  public static final int error = 1;
  public static final int POINTER = 17;
  public static final int ASSIGN = 9;
  public static final int RSQUARE = 16;
  public static final int ARRAY_OF = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "ASSIGN",
  "COMMA",
  "MOD",
  "NUMBER",
  "LBRACE",
  "RBRACE",
  "LSQUARE",
  "RSQUARE",
  "POINTER",
  "VALUE",
  "NAME",
  "CONST",
  "ARRAY_OF",
  "RETURN"
  };
}

