//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : AppClass.sm
//

#ifndef APPCLASS_SM_H
#define APPCLASS_SM_H


#define SMC_USES_IOSTREAMS

#include <statemap.h>

// Forward declarations.
class Map1;
class Map1_Start;
class Map1_TEL_FAX;
class Map1_SMS;
class Map1_NUMBER;
class Map1_DIGIT;
class Map1_PLUS;
class Map1_MESSAGE;
class Map1_CORRECT;
class Map1_Default;
class AppClassState;
class AppClassContext;
class AppClass;

class AppClassState :
    public statemap::State
{
public:

    AppClassState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(AppClassContext&) {};
    virtual void Exit(AppClassContext&) {};

    virtual void EOS(AppClassContext& context);
    virtual void cormes(AppClassContext& context);
    virtual void digit(AppClassContext& context);
    virtual void message(AppClassContext& context);
    virtual void number(AppClassContext& context);
    virtual void plus(AppClassContext& context);
    virtual void sms(AppClassContext& context);
    virtual void tel_fax(AppClassContext& context);
    virtual void wrong_begin(AppClassContext& context);
    virtual void wrong_message(AppClassContext& context);
    virtual void wrong_number(AppClassContext& context);

protected:

    virtual void Default(AppClassContext& context);
};

class Map1
{
public:

    static Map1_Start Start;
    static Map1_TEL_FAX TEL_FAX;
    static Map1_SMS SMS;
    static Map1_NUMBER NUMBER;
    static Map1_DIGIT DIGIT;
    static Map1_PLUS PLUS;
    static Map1_MESSAGE MESSAGE;
    static Map1_CORRECT CORRECT;
};

class Map1_Default :
    public AppClassState
{
public:

    Map1_Default(const char * const name, const int stateId)
    : AppClassState(name, stateId)
    {};

};

class Map1_Start :
    public Map1_Default
{
public:
    Map1_Start(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void sms(AppClassContext& context);
    virtual void tel_fax(AppClassContext& context);
    virtual void wrong_begin(AppClassContext& context);
};

class Map1_TEL_FAX :
    public Map1_Default
{
public:
    Map1_TEL_FAX(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void number(AppClassContext& context);
    virtual void wrong_number(AppClassContext& context);
};

class Map1_SMS :
    public Map1_Default
{
public:
    Map1_SMS(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void number(AppClassContext& context);
    virtual void wrong_number(AppClassContext& context);
};

class Map1_NUMBER :
    public Map1_Default
{
public:
    Map1_NUMBER(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void plus(AppClassContext& context);
    virtual void wrong_number(AppClassContext& context);
};

class Map1_DIGIT :
    public Map1_Default
{
public:
    Map1_DIGIT(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void EOS(AppClassContext& context);
    virtual void digit(AppClassContext& context);
    virtual void message(AppClassContext& context);
    virtual void number(AppClassContext& context);
    virtual void wrong_number(AppClassContext& context);
};

class Map1_PLUS :
    public Map1_Default
{
public:
    Map1_PLUS(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void digit(AppClassContext& context);
    virtual void message(AppClassContext& context);
    virtual void wrong_number(AppClassContext& context);
};

class Map1_MESSAGE :
    public Map1_Default
{
public:
    Map1_MESSAGE(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void EOS(AppClassContext& context);
    virtual void cormes(AppClassContext& context);
    virtual void digit(AppClassContext& context);
    virtual void message(AppClassContext& context);
    virtual void number(AppClassContext& context);
    virtual void plus(AppClassContext& context);
    virtual void wrong_message(AppClassContext& context);
};

class Map1_CORRECT :
    public Map1_Default
{
public:
    Map1_CORRECT(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void EOS(AppClassContext& context);
    virtual void cormes(AppClassContext& context);
    virtual void wrong_message(AppClassContext& context);
};

class AppClassContext :
    public statemap::FSMContext
{
public:

    explicit AppClassContext(AppClass& owner)
    : FSMContext(Map1::Start),
      _owner(owner)
    {};

    AppClassContext(AppClass& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline AppClass& getOwner()
    {
        return (_owner);
    };

    inline AppClassState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<AppClassState&>(*_state);
    };

    inline void EOS()
    {
        setTransition("EOS");
        getState().EOS(*this);
        setTransition(NULL);
    };

    inline void cormes()
    {
        setTransition("cormes");
        getState().cormes(*this);
        setTransition(NULL);
    };

    inline void digit()
    {
        setTransition("digit");
        getState().digit(*this);
        setTransition(NULL);
    };

    inline void message()
    {
        setTransition("message");
        getState().message(*this);
        setTransition(NULL);
    };

    inline void number()
    {
        setTransition("number");
        getState().number(*this);
        setTransition(NULL);
    };

    inline void plus()
    {
        setTransition("plus");
        getState().plus(*this);
        setTransition(NULL);
    };

    inline void sms()
    {
        setTransition("sms");
        getState().sms(*this);
        setTransition(NULL);
    };

    inline void tel_fax()
    {
        setTransition("tel_fax");
        getState().tel_fax(*this);
        setTransition(NULL);
    };

    inline void wrong_begin()
    {
        setTransition("wrong_begin");
        getState().wrong_begin(*this);
        setTransition(NULL);
    };

    inline void wrong_message()
    {
        setTransition("wrong_message");
        getState().wrong_message(*this);
        setTransition(NULL);
    };

    inline void wrong_number()
    {
        setTransition("wrong_number");
        getState().wrong_number(*this);
        setTransition(NULL);
    };

private:
    AppClass& _owner;
};


#endif // APPCLASS_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
